# Generated by Django 5.0.4 on 2024-04-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingrequest',
            name='accessible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='buildingNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='createdDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housingrequest',
            name='unitSize',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
