# Generated by Django 5.0.4 on 2024-04-15 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reservation_app', '0002_alter_housingrequest_accessible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='legalGuardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='room_reservation_app.legalguardian'),
        ),
    ]
