# Generated by Django 5.0.4 on 2024-04-20 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reservation_app', '0003_alter_student_legalguardian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingrequest',
            name='student',
        ),
        migrations.AddField(
            model_name='housingrequest',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='housingRequests', to=settings.AUTH_USER_MODEL),
        ),
    ]
