# Generated by Django 5.0.4 on 2024-04-30 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reservation_app', '0004_remove_housingrequest_student_housingrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommaterequest',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='roommateRequests', to=settings.AUTH_USER_MODEL),
        ),
    ]
