# Generated by Django 5.0.4 on 2024-05-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_reservation_app', '0005_roommaterequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommaterequest',
            name='housingRequest',
        ),
    ]
